// bootstrap_base_cons.go
// DO NOT EDIT THIS FILE WAS GENERATED AUTOMATICALLY BY https://github.com/zx80live/gofp-bootstrap

package fp

func (a Bool) Cons(b Bool) BoolList {
	return NilBoolList.Cons(a.Underlined()).Cons(b.Underlined())
}
func (a String) Cons(b String) StringList {
	return NilStringList.Cons(a.Underlined()).Cons(b.Underlined())
}
func (a Int) Cons(b Int) IntList {
	return NilIntList.Cons(a.Underlined()).Cons(b.Underlined())
}
func (a Int64) Cons(b Int64) Int64List {
	return NilInt64List.Cons(a.Underlined()).Cons(b.Underlined())
}
func (a Byte) Cons(b Byte) ByteList {
	return NilByteList.Cons(a.Underlined()).Cons(b.Underlined())
}
func (a Rune) Cons(b Rune) RuneList {
	return NilRuneList.Cons(a.Underlined()).Cons(b.Underlined())
}
func (a Float32) Cons(b Float32) Float32List {
	return NilFloat32List.Cons(a.Underlined()).Cons(b.Underlined())
}
func (a Float64) Cons(b Float64) Float64List {
	return NilFloat64List.Cons(a.Underlined()).Cons(b.Underlined())
}
