// bootstrap_list_size.go
// DO NOT EDIT THIS FILE WAS GENERATED AUTOMATICALLY BY https://github.com/zx80live/gofp-bootstrap

package fp

func (l BoolList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128List) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128OptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyArrayArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolOptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringOptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntOptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintOptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrOptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteOptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneOptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128OptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyOptionArrayOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyListOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128OptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyArrayArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolOptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringOptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntOptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintOptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrOptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteOptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneOptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128OptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyOptionArrayOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyListOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128OptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyArrayArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolOptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringOptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntOptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintOptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrOptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteOptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneOptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128OptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyOptionArrayOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyListOptionOptionOptionList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyArrayArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolOptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringOptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntOptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintOptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrOptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteOptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneOptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128OptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyOptionArrayList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l BoolListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l StringListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l IntListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int8ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int16ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int32ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Int64ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint8ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint16ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint32ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Uint64ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l UintptrListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l ByteListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l RuneListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float32ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Float64ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex64ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l Complex128ListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
func (l AnyListList) Size() int {
	count := 0
	xs := l
	for xs.NonEmpty() {
		count++
		xs = *xs.tail
	}
	return count
}
