// bootstrap_array_iterator_iterator.go
// DO NOT EDIT THIS FILE WAS GENERATED AUTOMATICALLY BY https://github.com/zx80live/gofp-bootstrap

package fp

func (a BoolArray) Iterator() BoolArrayIterator       { return BoolArrayIterator{0, len(a), &a} }
func (a StringArray) Iterator() StringArrayIterator   { return StringArrayIterator{0, len(a), &a} }
func (a IntArray) Iterator() IntArrayIterator         { return IntArrayIterator{0, len(a), &a} }
func (a Int64Array) Iterator() Int64ArrayIterator     { return Int64ArrayIterator{0, len(a), &a} }
func (a ByteArray) Iterator() ByteArrayIterator       { return ByteArrayIterator{0, len(a), &a} }
func (a RuneArray) Iterator() RuneArrayIterator       { return RuneArrayIterator{0, len(a), &a} }
func (a Float32Array) Iterator() Float32ArrayIterator { return Float32ArrayIterator{0, len(a), &a} }
func (a Float64Array) Iterator() Float64ArrayIterator { return Float64ArrayIterator{0, len(a), &a} }
func (a AnyArray) Iterator() AnyArrayIterator         { return AnyArrayIterator{0, len(a), &a} }
func (a Tuple2Array) Iterator() Tuple2ArrayIterator   { return Tuple2ArrayIterator{0, len(a), &a} }
func (a BoolArrayArray) Iterator() BoolArrayArrayIterator {
	return BoolArrayArrayIterator{0, len(a), &a}
}
func (a StringArrayArray) Iterator() StringArrayArrayIterator {
	return StringArrayArrayIterator{0, len(a), &a}
}
func (a IntArrayArray) Iterator() IntArrayArrayIterator { return IntArrayArrayIterator{0, len(a), &a} }
func (a Int64ArrayArray) Iterator() Int64ArrayArrayIterator {
	return Int64ArrayArrayIterator{0, len(a), &a}
}
func (a ByteArrayArray) Iterator() ByteArrayArrayIterator {
	return ByteArrayArrayIterator{0, len(a), &a}
}
func (a RuneArrayArray) Iterator() RuneArrayArrayIterator {
	return RuneArrayArrayIterator{0, len(a), &a}
}
func (a Float32ArrayArray) Iterator() Float32ArrayArrayIterator {
	return Float32ArrayArrayIterator{0, len(a), &a}
}
func (a Float64ArrayArray) Iterator() Float64ArrayArrayIterator {
	return Float64ArrayArrayIterator{0, len(a), &a}
}
func (a AnyArrayArray) Iterator() AnyArrayArrayIterator { return AnyArrayArrayIterator{0, len(a), &a} }
func (a Tuple2ArrayArray) Iterator() Tuple2ArrayArrayIterator {
	return Tuple2ArrayArrayIterator{0, len(a), &a}
}
