// bootstrap_option_none.go
// DO NOT EDIT THIS FILE WAS GENERATED AUTOMATICALLY BY https://github.com/zx80live/gofp-bootstrap

package fp


var NoneBool BoolOption = BoolOption { nil }
var NoneString StringOption = StringOption { nil }
var NoneInt IntOption = IntOption { nil }
var NoneInt64 Int64Option = Int64Option { nil }
var NoneByte ByteOption = ByteOption { nil }
var NoneRune RuneOption = RuneOption { nil }
var NoneFloat32 Float32Option = Float32Option { nil }
var NoneFloat64 Float64Option = Float64Option { nil }
var NoneAny AnyOption = AnyOption { nil }
var NoneTuple2 Tuple2Option = Tuple2Option { nil }
var NoneBoolOption BoolOptionOption = BoolOptionOption { nil }
var NoneStringOption StringOptionOption = StringOptionOption { nil }
var NoneIntOption IntOptionOption = IntOptionOption { nil }
var NoneInt64Option Int64OptionOption = Int64OptionOption { nil }
var NoneByteOption ByteOptionOption = ByteOptionOption { nil }
var NoneRuneOption RuneOptionOption = RuneOptionOption { nil }
var NoneFloat32Option Float32OptionOption = Float32OptionOption { nil }
var NoneFloat64Option Float64OptionOption = Float64OptionOption { nil }
var NoneAnyOption AnyOptionOption = AnyOptionOption { nil }
var NoneTuple2Option Tuple2OptionOption = Tuple2OptionOption { nil }
var NoneBoolArray BoolArrayOption = BoolArrayOption { nil }
var NoneStringArray StringArrayOption = StringArrayOption { nil }
var NoneIntArray IntArrayOption = IntArrayOption { nil }
var NoneInt64Array Int64ArrayOption = Int64ArrayOption { nil }
var NoneByteArray ByteArrayOption = ByteArrayOption { nil }
var NoneRuneArray RuneArrayOption = RuneArrayOption { nil }
var NoneFloat32Array Float32ArrayOption = Float32ArrayOption { nil }
var NoneFloat64Array Float64ArrayOption = Float64ArrayOption { nil }
var NoneAnyArray AnyArrayOption = AnyArrayOption { nil }
var NoneTuple2Array Tuple2ArrayOption = Tuple2ArrayOption { nil }
var NoneBoolList BoolListOption = BoolListOption { nil }
var NoneStringList StringListOption = StringListOption { nil }
var NoneIntList IntListOption = IntListOption { nil }
var NoneInt64List Int64ListOption = Int64ListOption { nil }
var NoneByteList ByteListOption = ByteListOption { nil }
var NoneRuneList RuneListOption = RuneListOption { nil }
var NoneFloat32List Float32ListOption = Float32ListOption { nil }
var NoneFloat64List Float64ListOption = Float64ListOption { nil }
var NoneAnyList AnyListOption = AnyListOption { nil }
var NoneTuple2List Tuple2ListOption = Tuple2ListOption { nil }