// flist_tail.go
// DO NOT EDIT THIS FILE WAS GENERATED AUTOMATICALLY BY gofp-bootstrap

package fp

func (l ListBool) Tail() ListBool                   { return l.tail.Copy() }
func (l ListRune) Tail() ListRune                   { return l.tail.Copy() }
func (l ListByte) Tail() ListByte                   { return l.tail.Copy() }
func (l ListInt) Tail() ListInt                     { return l.tail.Copy() }
func (l ListInt8) Tail() ListInt8                   { return l.tail.Copy() }
func (l ListInt16) Tail() ListInt16                 { return l.tail.Copy() }
func (l ListInt32) Tail() ListInt32                 { return l.tail.Copy() }
func (l ListInt64) Tail() ListInt64                 { return l.tail.Copy() }
func (l ListUint) Tail() ListUint                   { return l.tail.Copy() }
func (l ListUint8) Tail() ListUint8                 { return l.tail.Copy() }
func (l ListUint16) Tail() ListUint16               { return l.tail.Copy() }
func (l ListUint32) Tail() ListUint32               { return l.tail.Copy() }
func (l ListUint64) Tail() ListUint64               { return l.tail.Copy() }
func (l ListUintptr) Tail() ListUintptr             { return l.tail.Copy() }
func (l ListFloat32) Tail() ListFloat32             { return l.tail.Copy() }
func (l ListFloat64) Tail() ListFloat64             { return l.tail.Copy() }
func (l ListComplex64) Tail() ListComplex64         { return l.tail.Copy() }
func (l ListComplex128) Tail() ListComplex128       { return l.tail.Copy() }
func (l ListString) Tail() ListString               { return l.tail.Copy() }
func (l ListInterface) Tail() ListInterface         { return l.tail.Copy() }
func (l ListBoolArr) Tail() ListBoolArr             { return l.tail.Copy() }
func (l ListRuneArr) Tail() ListRuneArr             { return l.tail.Copy() }
func (l ListByteArr) Tail() ListByteArr             { return l.tail.Copy() }
func (l ListIntArr) Tail() ListIntArr               { return l.tail.Copy() }
func (l ListInt8Arr) Tail() ListInt8Arr             { return l.tail.Copy() }
func (l ListInt16Arr) Tail() ListInt16Arr           { return l.tail.Copy() }
func (l ListInt32Arr) Tail() ListInt32Arr           { return l.tail.Copy() }
func (l ListInt64Arr) Tail() ListInt64Arr           { return l.tail.Copy() }
func (l ListUintArr) Tail() ListUintArr             { return l.tail.Copy() }
func (l ListUint8Arr) Tail() ListUint8Arr           { return l.tail.Copy() }
func (l ListUint16Arr) Tail() ListUint16Arr         { return l.tail.Copy() }
func (l ListUint32Arr) Tail() ListUint32Arr         { return l.tail.Copy() }
func (l ListUint64Arr) Tail() ListUint64Arr         { return l.tail.Copy() }
func (l ListUintptrArr) Tail() ListUintptrArr       { return l.tail.Copy() }
func (l ListFloat32Arr) Tail() ListFloat32Arr       { return l.tail.Copy() }
func (l ListFloat64Arr) Tail() ListFloat64Arr       { return l.tail.Copy() }
func (l ListComplex64Arr) Tail() ListComplex64Arr   { return l.tail.Copy() }
func (l ListComplex128Arr) Tail() ListComplex128Arr { return l.tail.Copy() }
func (l ListStringArr) Tail() ListStringArr         { return l.tail.Copy() }
func (l ListInterfaceArr) Tail() ListInterfaceArr   { return l.tail.Copy() }
