// ftuple.go
// DO NOT EDIT THIS FILE WAS GENERATED AUTOMATICALLY BY gofp-bootstrap

package fp

type Tuple1 struct {
	E1 Any
}

type Tuple2 struct {
	E1 Any
	E2 Any
}

type Tuple3 struct {
	E1 Any
	E2 Any
	E3 Any
}

type Tuple4 struct {
	E1 Any
	E2 Any
	E3 Any
	E4 Any
}

type Tuple5 struct {
	E1 Any
	E2 Any
	E3 Any
	E4 Any
	E5 Any
}

type Tuple6 struct {
	E1 Any
	E2 Any
	E3 Any
	E4 Any
	E5 Any
	E6 Any
}

type Tuple7 struct {
	E1 Any
	E2 Any
	E3 Any
	E4 Any
	E5 Any
	E6 Any
	E7 Any
}

type Tuple8 struct {
	E1 Any
	E2 Any
	E3 Any
	E4 Any
	E5 Any
	E6 Any
	E7 Any
	E8 Any
}

type Tuple9 struct {
	E1 Any
	E2 Any
	E3 Any
	E4 Any
	E5 Any
	E6 Any
	E7 Any
	E8 Any
	E9 Any
}

type Tuple10 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
}

type Tuple11 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
}

type Tuple12 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
}

type Tuple13 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
}

type Tuple14 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
}

type Tuple15 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
}

type Tuple16 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
}

type Tuple17 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
}

type Tuple18 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
}

type Tuple19 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
}

type Tuple20 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
}

type Tuple21 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
}

type Tuple22 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
	E22 Any
}

type Tuple23 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
	E22 Any
	E23 Any
}

type Tuple24 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
	E22 Any
	E23 Any
	E24 Any
}

type Tuple25 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
	E22 Any
	E23 Any
	E24 Any
	E25 Any
}

type Tuple26 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
	E22 Any
	E23 Any
	E24 Any
	E25 Any
	E26 Any
}

type Tuple27 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
	E22 Any
	E23 Any
	E24 Any
	E25 Any
	E26 Any
	E27 Any
}

type Tuple28 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
	E22 Any
	E23 Any
	E24 Any
	E25 Any
	E26 Any
	E27 Any
	E28 Any
}

type Tuple29 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
	E22 Any
	E23 Any
	E24 Any
	E25 Any
	E26 Any
	E27 Any
	E28 Any
	E29 Any
}

type Tuple30 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
	E22 Any
	E23 Any
	E24 Any
	E25 Any
	E26 Any
	E27 Any
	E28 Any
	E29 Any
	E30 Any
}

type Tuple31 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
	E22 Any
	E23 Any
	E24 Any
	E25 Any
	E26 Any
	E27 Any
	E28 Any
	E29 Any
	E30 Any
	E31 Any
}

type Tuple32 struct {
	E1  Any
	E2  Any
	E3  Any
	E4  Any
	E5  Any
	E6  Any
	E7  Any
	E8  Any
	E9  Any
	E10 Any
	E11 Any
	E12 Any
	E13 Any
	E14 Any
	E15 Any
	E16 Any
	E17 Any
	E18 Any
	E19 Any
	E20 Any
	E21 Any
	E22 Any
	E23 Any
	E24 Any
	E25 Any
	E26 Any
	E27 Any
	E28 Any
	E29 Any
	E30 Any
	E31 Any
	E32 Any
}
