// bootstrap_linkedlist_foreach.go
// DO NOT EDIT THIS FILE WAS GENERATED AUTOMATICALLY BY https://github.com/zx80live/gofp-bootstrap

package fp

import . "github.com/zx80live/gofp/fp"

func (n *BoolLinkedList) Foreach(f func(bool)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *StringLinkedList) Foreach(f func(string)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *IntLinkedList) Foreach(f func(int)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Int64LinkedList) Foreach(f func(int64)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *ByteLinkedList) Foreach(f func(byte)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *RuneLinkedList) Foreach(f func(rune)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Float32LinkedList) Foreach(f func(float32)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Float64LinkedList) Foreach(f func(float64)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *AnyLinkedList) Foreach(f func(Any)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Tuple2LinkedList) Foreach(f func(Tuple2)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *BoolArrayLinkedList) Foreach(f func([]bool)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *StringArrayLinkedList) Foreach(f func([]string)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *IntArrayLinkedList) Foreach(f func([]int)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Int64ArrayLinkedList) Foreach(f func([]int64)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *ByteArrayLinkedList) Foreach(f func([]byte)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *RuneArrayLinkedList) Foreach(f func([]rune)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Float32ArrayLinkedList) Foreach(f func([]float32)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Float64ArrayLinkedList) Foreach(f func([]float64)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *AnyArrayLinkedList) Foreach(f func([]Any)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Tuple2ArrayLinkedList) Foreach(f func([]Tuple2)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *BoolOptionLinkedList) Foreach(f func(BoolOption)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *StringOptionLinkedList) Foreach(f func(StringOption)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *IntOptionLinkedList) Foreach(f func(IntOption)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Int64OptionLinkedList) Foreach(f func(Int64Option)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *ByteOptionLinkedList) Foreach(f func(ByteOption)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *RuneOptionLinkedList) Foreach(f func(RuneOption)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Float32OptionLinkedList) Foreach(f func(Float32Option)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Float64OptionLinkedList) Foreach(f func(Float64Option)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *AnyOptionLinkedList) Foreach(f func(AnyOption)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Tuple2OptionLinkedList) Foreach(f func(Tuple2Option)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *BoolLinkedListLinkedList) Foreach(f func(BoolLinkedList)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *StringLinkedListLinkedList) Foreach(f func(StringLinkedList)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *IntLinkedListLinkedList) Foreach(f func(IntLinkedList)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Int64LinkedListLinkedList) Foreach(f func(Int64LinkedList)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *ByteLinkedListLinkedList) Foreach(f func(ByteLinkedList)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *RuneLinkedListLinkedList) Foreach(f func(RuneLinkedList)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Float32LinkedListLinkedList) Foreach(f func(Float32LinkedList)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Float64LinkedListLinkedList) Foreach(f func(Float64LinkedList)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *AnyLinkedListLinkedList) Foreach(f func(AnyLinkedList)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
func (n *Tuple2LinkedListLinkedList) Foreach(f func(Tuple2LinkedList)) {
	h := n.head
	for {
		h = h.next
		if h == nil {
			return
		}
		f(*h.value)
	}
}
