// bootstrap_linkedlist.go
// DO NOT EDIT THIS FILE WAS GENERATED AUTOMATICALLY BY https://github.com/zx80live/gofp-bootstrap

package fp

import . "github.com/zx80live/gofp/fp"

type BoolLinkedList struct {
	value *bool
	head  *BoolLinkedList
	end   *BoolLinkedList
	prev  *BoolLinkedList
	next  *BoolLinkedList
}
type StringLinkedList struct {
	value *string
	head  *StringLinkedList
	end   *StringLinkedList
	prev  *StringLinkedList
	next  *StringLinkedList
}
type IntLinkedList struct {
	value *int
	head  *IntLinkedList
	end   *IntLinkedList
	prev  *IntLinkedList
	next  *IntLinkedList
}
type Int64LinkedList struct {
	value *int64
	head  *Int64LinkedList
	end   *Int64LinkedList
	prev  *Int64LinkedList
	next  *Int64LinkedList
}
type ByteLinkedList struct {
	value *byte
	head  *ByteLinkedList
	end   *ByteLinkedList
	prev  *ByteLinkedList
	next  *ByteLinkedList
}
type RuneLinkedList struct {
	value *rune
	head  *RuneLinkedList
	end   *RuneLinkedList
	prev  *RuneLinkedList
	next  *RuneLinkedList
}
type Float32LinkedList struct {
	value *float32
	head  *Float32LinkedList
	end   *Float32LinkedList
	prev  *Float32LinkedList
	next  *Float32LinkedList
}
type Float64LinkedList struct {
	value *float64
	head  *Float64LinkedList
	end   *Float64LinkedList
	prev  *Float64LinkedList
	next  *Float64LinkedList
}
type AnyLinkedList struct {
	value *Any
	head  *AnyLinkedList
	end   *AnyLinkedList
	prev  *AnyLinkedList
	next  *AnyLinkedList
}
type Tuple2LinkedList struct {
	value *Tuple2
	head  *Tuple2LinkedList
	end   *Tuple2LinkedList
	prev  *Tuple2LinkedList
	next  *Tuple2LinkedList
}
type BoolArrayLinkedList struct {
	value *[]bool
	head  *BoolArrayLinkedList
	end   *BoolArrayLinkedList
	prev  *BoolArrayLinkedList
	next  *BoolArrayLinkedList
}
type StringArrayLinkedList struct {
	value *[]string
	head  *StringArrayLinkedList
	end   *StringArrayLinkedList
	prev  *StringArrayLinkedList
	next  *StringArrayLinkedList
}
type IntArrayLinkedList struct {
	value *[]int
	head  *IntArrayLinkedList
	end   *IntArrayLinkedList
	prev  *IntArrayLinkedList
	next  *IntArrayLinkedList
}
type Int64ArrayLinkedList struct {
	value *[]int64
	head  *Int64ArrayLinkedList
	end   *Int64ArrayLinkedList
	prev  *Int64ArrayLinkedList
	next  *Int64ArrayLinkedList
}
type ByteArrayLinkedList struct {
	value *[]byte
	head  *ByteArrayLinkedList
	end   *ByteArrayLinkedList
	prev  *ByteArrayLinkedList
	next  *ByteArrayLinkedList
}
type RuneArrayLinkedList struct {
	value *[]rune
	head  *RuneArrayLinkedList
	end   *RuneArrayLinkedList
	prev  *RuneArrayLinkedList
	next  *RuneArrayLinkedList
}
type Float32ArrayLinkedList struct {
	value *[]float32
	head  *Float32ArrayLinkedList
	end   *Float32ArrayLinkedList
	prev  *Float32ArrayLinkedList
	next  *Float32ArrayLinkedList
}
type Float64ArrayLinkedList struct {
	value *[]float64
	head  *Float64ArrayLinkedList
	end   *Float64ArrayLinkedList
	prev  *Float64ArrayLinkedList
	next  *Float64ArrayLinkedList
}
type AnyArrayLinkedList struct {
	value *[]Any
	head  *AnyArrayLinkedList
	end   *AnyArrayLinkedList
	prev  *AnyArrayLinkedList
	next  *AnyArrayLinkedList
}
type Tuple2ArrayLinkedList struct {
	value *[]Tuple2
	head  *Tuple2ArrayLinkedList
	end   *Tuple2ArrayLinkedList
	prev  *Tuple2ArrayLinkedList
	next  *Tuple2ArrayLinkedList
}
type BoolOptionLinkedList struct {
	value *BoolOption
	head  *BoolOptionLinkedList
	end   *BoolOptionLinkedList
	prev  *BoolOptionLinkedList
	next  *BoolOptionLinkedList
}
type StringOptionLinkedList struct {
	value *StringOption
	head  *StringOptionLinkedList
	end   *StringOptionLinkedList
	prev  *StringOptionLinkedList
	next  *StringOptionLinkedList
}
type IntOptionLinkedList struct {
	value *IntOption
	head  *IntOptionLinkedList
	end   *IntOptionLinkedList
	prev  *IntOptionLinkedList
	next  *IntOptionLinkedList
}
type Int64OptionLinkedList struct {
	value *Int64Option
	head  *Int64OptionLinkedList
	end   *Int64OptionLinkedList
	prev  *Int64OptionLinkedList
	next  *Int64OptionLinkedList
}
type ByteOptionLinkedList struct {
	value *ByteOption
	head  *ByteOptionLinkedList
	end   *ByteOptionLinkedList
	prev  *ByteOptionLinkedList
	next  *ByteOptionLinkedList
}
type RuneOptionLinkedList struct {
	value *RuneOption
	head  *RuneOptionLinkedList
	end   *RuneOptionLinkedList
	prev  *RuneOptionLinkedList
	next  *RuneOptionLinkedList
}
type Float32OptionLinkedList struct {
	value *Float32Option
	head  *Float32OptionLinkedList
	end   *Float32OptionLinkedList
	prev  *Float32OptionLinkedList
	next  *Float32OptionLinkedList
}
type Float64OptionLinkedList struct {
	value *Float64Option
	head  *Float64OptionLinkedList
	end   *Float64OptionLinkedList
	prev  *Float64OptionLinkedList
	next  *Float64OptionLinkedList
}
type AnyOptionLinkedList struct {
	value *AnyOption
	head  *AnyOptionLinkedList
	end   *AnyOptionLinkedList
	prev  *AnyOptionLinkedList
	next  *AnyOptionLinkedList
}
type Tuple2OptionLinkedList struct {
	value *Tuple2Option
	head  *Tuple2OptionLinkedList
	end   *Tuple2OptionLinkedList
	prev  *Tuple2OptionLinkedList
	next  *Tuple2OptionLinkedList
}
type BoolLinkedListLinkedList struct {
	value *BoolLinkedList
	head  *BoolLinkedListLinkedList
	end   *BoolLinkedListLinkedList
	prev  *BoolLinkedListLinkedList
	next  *BoolLinkedListLinkedList
}
type StringLinkedListLinkedList struct {
	value *StringLinkedList
	head  *StringLinkedListLinkedList
	end   *StringLinkedListLinkedList
	prev  *StringLinkedListLinkedList
	next  *StringLinkedListLinkedList
}
type IntLinkedListLinkedList struct {
	value *IntLinkedList
	head  *IntLinkedListLinkedList
	end   *IntLinkedListLinkedList
	prev  *IntLinkedListLinkedList
	next  *IntLinkedListLinkedList
}
type Int64LinkedListLinkedList struct {
	value *Int64LinkedList
	head  *Int64LinkedListLinkedList
	end   *Int64LinkedListLinkedList
	prev  *Int64LinkedListLinkedList
	next  *Int64LinkedListLinkedList
}
type ByteLinkedListLinkedList struct {
	value *ByteLinkedList
	head  *ByteLinkedListLinkedList
	end   *ByteLinkedListLinkedList
	prev  *ByteLinkedListLinkedList
	next  *ByteLinkedListLinkedList
}
type RuneLinkedListLinkedList struct {
	value *RuneLinkedList
	head  *RuneLinkedListLinkedList
	end   *RuneLinkedListLinkedList
	prev  *RuneLinkedListLinkedList
	next  *RuneLinkedListLinkedList
}
type Float32LinkedListLinkedList struct {
	value *Float32LinkedList
	head  *Float32LinkedListLinkedList
	end   *Float32LinkedListLinkedList
	prev  *Float32LinkedListLinkedList
	next  *Float32LinkedListLinkedList
}
type Float64LinkedListLinkedList struct {
	value *Float64LinkedList
	head  *Float64LinkedListLinkedList
	end   *Float64LinkedListLinkedList
	prev  *Float64LinkedListLinkedList
	next  *Float64LinkedListLinkedList
}
type AnyLinkedListLinkedList struct {
	value *AnyLinkedList
	head  *AnyLinkedListLinkedList
	end   *AnyLinkedListLinkedList
	prev  *AnyLinkedListLinkedList
	next  *AnyLinkedListLinkedList
}
type Tuple2LinkedListLinkedList struct {
	value *Tuple2LinkedList
	head  *Tuple2LinkedListLinkedList
	end   *Tuple2LinkedListLinkedList
	prev  *Tuple2LinkedListLinkedList
	next  *Tuple2LinkedListLinkedList
}
